from django.db import models

# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class greenbook(models.Model):
    companycode = models.CharField(max_length=200, null=True, blank=True)
    recordid = models.IntegerField(null=True, blank=True)
    dels = models.IntegerField(null=True, blank=True)
    vehiclekey = models.CharField(max_length=200, null=True, blank=True)
    vehicletypecode = models.CharField(max_length=200, null=True, blank=True)
    yeargroup = models.IntegerField(null=True, blank=True)
    monthgroup = models.IntegerField(null=True, blank=True)
    auctmakecode = models.CharField(max_length=200, null=True, blank=True)
    makecode = models.CharField(max_length=200, null=True, blank=True)
    makename = models.CharField(max_length=200, null=True, blank=True)
    auctfamilycode = models.CharField(max_length=200, null=True, blank=True)
    familycode = models.CharField(max_length=200, null=True, blank=True)
    familyname = models.CharField(max_length=200, null=True, blank=True)
    submodeldesc = models.CharField(max_length=200, null=True, blank=True)
    submodeldesc2 = models.CharField(max_length=200, null=True, blank=True)
    modelss = models.IntegerField(null=True, blank=True)
    modelf = models.CharField(max_length=200, null=True, blank=True)
    nickname = models.CharField(max_length=200, null=True, blank=True)
    submodelname = models.CharField(max_length=200, null=True, blank=True)
    series = models.CharField(max_length=200, null=True, blank=True)
    badgedescription = models.CharField(max_length=200, null=True, blank=True)
    badgesecondarydescription = models.CharField(max_length=200, null=True, blank=True)
    bodystyledescription = models.CharField(max_length=200, null=True, blank=True)
    bodyconfigdescription = models.CharField(max_length=200, null=True, blank=True)
    extraidentification = models.CharField(max_length=200, null=True, blank=True)
    drive = models.CharField(max_length=200, null=True, blank=True)
    gear = models.CharField(max_length=200, null=True, blank=True)
    gearnum = models.FloatField(null=True, blank=True)
    doornum = models.IntegerField(null=True, blank=True)
    enginesize = models.FloatField(null=True, blank=True)
    enginedescription = models.FloatField(null=True, blank=True)
    cc = models.FloatField(null=True, blank=True)
    fuel = models.CharField(max_length=200, null=True, blank=True)
    avgwholesale = models.IntegerField(null=True, blank=True)
    avgretail = models.IntegerField(null=True, blank=True)
    goodwholesale = models.IntegerField(null=True, blank=True)
    goodretail = models.IntegerField(null=True, blank=True)
    newprice = models.FloatField(null=True, blank=True)
    vin = models.CharField(max_length=200, null=True, blank=True)
    modelcode = models.CharField(max_length=200, null=True, blank=True)
    enginenum = models.CharField(max_length=200, null=True, blank=True)
    showstat = models.FloatField(null=True, blank=True)
    brand = models.FloatField(null=True, blank=True)
    buildcountryorigindescription = models.CharField(max_length=200, null=True, blank=True)
    auctbodyname = models.CharField(max_length=200, null=True, blank=True)
    created_by = models.FloatField(null=True, blank=True)
    created_date = models.FloatField(null=True, blank=True)
    last_modified_by = models.FloatField(null=True, blank=True)
    last_modified_date = models.FloatField(null=True, blank=True)
    cancelled = models.IntegerField(null=True, blank=True)
    cancelled_datetime = models.FloatField(null=True, blank=True)
    cancelled_by = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.vehiclekey

class asset_sold_car_2024_2025(models.Model):
    byQuater = models.IntegerField(null=True, blank=True)
    byMonth = models.IntegerField(null=True, blank=True)
    Month_Name = models.CharField(max_length=200, null=True, blank=True)
    bySeasonal = models.CharField(max_length=200, null=True, blank=True)
    Branch_Code = models.IntegerField(null=True, blank=True)
    Branch_Name = models.CharField(max_length=200, null=True, blank=True)
    Floor = models.CharField(max_length=200, null=True, blank=True)
    Auction_No = models.IntegerField(null=True, blank=True)
    MakeCode = models.CharField(max_length=200, null=True, blank=True)
    Brand_Name = models.CharField(max_length=200, null=True, blank=True)
    Model_Name = models.CharField(max_length=200, null=True, blank=True)
    Sub_Model_Code = models.CharField(max_length=200, null=True, blank=True)
    Sub_Key = models.CharField(max_length=200, null=True, blank=True)
    Asset_Gear = models.CharField(max_length=200, null=True, blank=True)
    Engine_Size = models.FloatField(null=True, blank=True)
    Chassis_No = models.CharField(max_length=200, null=True, blank=True)
    Engine_No = models.CharField(max_length=200, null=True, blank=True)
    Mile = models.FloatField(null=True, blank=True)
    Color_in_copy = models.CharField(max_length=200, null=True, blank=True)
    Year_of_Manufacture = models.IntegerField(null=True, blank=True)
    Asset_Register_Year = models.FloatField(null=True, blank=True)
    Asset_Type_Code = models.CharField(max_length=200, null=True, blank=True)
    Asset_Type_Name = models.CharField(max_length=200, null=True, blank=True)
    Asset_Group_Code = models.CharField(max_length=200, null=True, blank=True)
    Asset_Group_Name = models.CharField(max_length=200, null=True, blank=True)
    Asset_Grade_Assessment = models.CharField(max_length=200, null=True, blank=True)
    Sales_Price = models.FloatField(null=True, blank=True)
    Vat_Amount = models.FloatField(null=True, blank=True)
    VAT_Code = models.CharField(max_length=200, null=True, blank=True)
    Vat_Percentage = models.IntegerField(null=True, blank=True)
    Price_including_VAT = models.FloatField(null=True, blank=True)
    Seller_Approve_Sales_Price = models.IntegerField(null=True, blank=True)
    Approve_Sales_Price = models.IntegerField(null=True, blank=True)
    Sold_Amount = models.FloatField(null=True, blank=True)
    Sales_Type = models.CharField(max_length=200, null=True, blank=True)
    Asset_Code = models.CharField(max_length=200, null=True, blank=True)
    Contract_No = models.CharField(max_length=200, null=True, blank=True)
    License_Plate_No = models.CharField(max_length=200, null=True, blank=True)
    License_Plate_City = models.CharField(max_length=200, null=True, blank=True)
    License_Plate_Name = models.CharField(max_length=200, null=True, blank=True)
    Seller_Code = models.CharField(max_length=200, null=True, blank=True)
    Asset_Name = models.CharField(max_length=200, null=True, blank=True)
    Highest_Selling_Price = models.IntegerField(null=True, blank=True)
    Asset_Tax_Due_Date = models.CharField(max_length=200, null=True, blank=True)
    Accessories = models.FloatField(null=True, blank=True)
    Auction_Board = models.IntegerField(null=True, blank=True)
    Asset_Grade = models.CharField(max_length=200, null=True, blank=True)
    Asset_Grade_Check_Condition = models.CharField(max_length=200, null=True, blank=True)
    Vendor_No = models.CharField(max_length=200, null=True, blank=True)
    Vendor_Name = models.CharField(max_length=200, null=True, blank=True)
    Vendor_Type = models.CharField(max_length=200, null=True, blank=True)
    sale_remark = models.CharField(max_length=200, null=True, blank=True)
    Vehiclekey = models.CharField(max_length=200, null=True, blank=True)
    BodyStyleDescription = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.Sub_Key} {self.Brand_Name} {self.Model_Name} {self.Sub_Model_Code}"
    
class asset_sold_car_test(models.Model):
    auction_date =  models.DateField(blank=True, null=True)
    byquater = models.IntegerField(null=True, blank=True)
    bymonth = models.IntegerField(null=True, blank=True)
    month_name = models.CharField(max_length=200, null=True, blank=True)
    byseasonal = models.CharField(max_length=200, null=True, blank=True)
    branch_code = models.IntegerField(null=True, blank=True)
    branch_name = models.CharField(max_length=200, null=True, blank=True)
    floor = models.CharField(max_length=200, null=True, blank=True)
    auction_no = models.IntegerField(null=True, blank=True)
    makecode = models.CharField(max_length=200, null=True, blank=True)
    brand_name = models.CharField(max_length=200, null=True, blank=True)
    model_name = models.CharField(max_length=200, null=True, blank=True)
    sub_model_code = models.CharField(max_length=200, null=True, blank=True)
    sub_key = models.CharField(max_length=200, null=True, blank=True)
    asset_gear = models.CharField(max_length=200, null=True, blank=True)
    engine_size = models.FloatField(null=True, blank=True)
    chassis_no = models.CharField(max_length=200, null=True, blank=True)
    engine_no = models.CharField(max_length=200, null=True, blank=True)
    mile = models.FloatField(null=True, blank=True)
    color_in_copy = models.CharField(max_length=200, null=True, blank=True)
    year_of_manufacture = models.IntegerField(null=True, blank=True)
    asset_register_year = models.FloatField(null=True, blank=True)
    asset_type_code = models.CharField(max_length=200, null=True, blank=True)
    asset_type_name = models.CharField(max_length=200, null=True, blank=True)
    asset_group_code = models.CharField(max_length=200, null=True, blank=True)
    asset_group_name = models.CharField(max_length=200, null=True, blank=True)
    asset_grade_assessment = models.CharField(max_length=200, null=True, blank=True)
    sales_price = models.FloatField(null=True, blank=True)
    vat_amount = models.FloatField(null=True, blank=True)
    vat_code = models.CharField(max_length=200, null=True, blank=True)
    vat_percentage = models.IntegerField(null=True, blank=True)
    price_including_vat = models.FloatField(null=True, blank=True)
    seller_approve_sales_price = models.IntegerField(null=True, blank=True)
    approve_sales_price = models.IntegerField(null=True, blank=True)
    sold_amount = models.FloatField(null=True, blank=True)
    sales_type = models.CharField(max_length=200, null=True, blank=True)
    asset_code = models.CharField(max_length=200, null=True, blank=True)
    contract_no = models.CharField(max_length=200, null=True, blank=True)
    license_plate_no = models.CharField(max_length=200, null=True, blank=True)
    license_plate_city = models.CharField(max_length=200, null=True, blank=True)
    license_plate_name = models.CharField(max_length=200, null=True, blank=True)
    seller_code = models.CharField(max_length=200, null=True, blank=True)
    asset_name = models.CharField(max_length=200, null=True, blank=True)
    highest_selling_price = models.IntegerField(null=True, blank=True)
    asset_tax_due_date = models.CharField(max_length=200, null=True, blank=True)
    accessories = models.FloatField(null=True, blank=True)
    auction_board = models.IntegerField(null=True, blank=True)
    asset_grade = models.CharField(max_length=200, null=True, blank=True)
    asset_grade_check_condition = models.CharField(max_length=200, null=True, blank=True)
    vendor_no = models.CharField(max_length=200, null=True, blank=True)
    vendor_name = models.CharField(max_length=200, null=True, blank=True)
    vendor_type = models.CharField(max_length=200, null=True, blank=True)
    sale_remark = models.CharField(max_length=200, null=True, blank=True)
    vehiclekey = models.CharField(max_length=200, null=True, blank=True)
    bodystyledescription = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.sub_key} {self.brand_name} {self.model_name} {self.sub_model_code}"   