# Generated by Django 4.2 on 2026-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='greenbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companycode', models.CharField(max_length=200)),
                ('recordid', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('vehiclekey', models.CharField(max_length=200)),
                ('vehicletypecode', models.CharField(max_length=200)),
                ('yeargroup', models.IntegerField()),
                ('monthgroup', models.IntegerField()),
                ('auctmakecode', models.CharField(max_length=200)),
                ('makecode', models.CharField(max_length=200)),
                ('makename', models.CharField(max_length=200)),
                ('auctfamilycode', models.CharField(max_length=200)),
                ('familycode', models.CharField(max_length=200)),
                ('familyname', models.CharField(max_length=200)),
                ('submodeldesc', models.CharField(max_length=200)),
                ('submodeldesc2', models.CharField(max_length=200)),
                ('modelss', models.IntegerField()),
                ('modelf', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('submodelname', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('badgedescription', models.CharField(max_length=200)),
                ('badgesecondarydescription', models.CharField(max_length=200)),
                ('bodystyledescription', models.CharField(max_length=200)),
                ('bodyconfigdescription', models.CharField(max_length=200)),
                ('extraidentification', models.CharField(max_length=200)),
                ('drive', models.CharField(max_length=200)),
                ('gear', models.CharField(max_length=200)),
                ('gearnum', models.FloatField()),
                ('doornum', models.IntegerField()),
                ('enginesize', models.FloatField()),
                ('enginedescription', models.FloatField()),
                ('cc', models.FloatField()),
                ('fuel', models.CharField(max_length=200)),
                ('avgwholesale', models.IntegerField()),
                ('avgretail', models.IntegerField()),
                ('goodwholesale', models.IntegerField()),
                ('goodretail', models.IntegerField()),
                ('newprice', models.FloatField()),
                ('vin', models.CharField(max_length=200)),
                ('modelcode', models.CharField(max_length=200)),
                ('enginenum', models.CharField(max_length=200)),
                ('showstat', models.FloatField()),
                ('brand', models.FloatField()),
                ('buildcountryorigindescription', models.CharField(max_length=200)),
                ('auctbodyname', models.CharField(max_length=200)),
                ('created_by', models.FloatField()),
                ('created_date', models.DateTimeField()),
                ('last_modified_by', models.FloatField()),
                ('last_modified_date', models.DateTimeField()),
                ('cancelled', models.IntegerField()),
                ('cancelled_datetime', models.DateTimeField()),
                ('cancelled_by', models.FloatField()),
            ],
        ),
    ]
