# Generated by Django 4.2 on 2026-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenbook', '0002_greenbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenbook',
            name='auctbodyname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='auctfamilycode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='auctmakecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='avgretail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='avgwholesale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='badgedescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='badgesecondarydescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='bodyconfigdescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='bodystyledescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='brand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='buildcountryorigindescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='cancelled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='cancelled_by',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='cancelled_datetime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='cc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='companycode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='created_by',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='created_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='dels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='doornum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='drive',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='enginedescription',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='enginenum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='enginesize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='extraidentification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='familycode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='familyname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='fuel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='gear',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='gearnum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='goodretail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='goodwholesale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='last_modified_by',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='last_modified_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='makecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='makename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='modelcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='modelf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='modelss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='monthgroup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='newprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='recordid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='showstat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='submodeldesc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='submodeldesc2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='submodelname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='vehiclekey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='vehicletypecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='vin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenbook',
            name='yeargroup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
