# Generated by Django 4.2 on 2026-03-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenbook', '0003_alter_greenbook_auctbodyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_sold_car_2024_2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byQuater', models.IntegerField(blank=True, null=True)),
                ('byMonth', models.IntegerField(blank=True, null=True)),
                ('Month_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('bySeasonal', models.CharField(blank=True, max_length=200, null=True)),
                ('Branch_Code', models.IntegerField(blank=True, null=True)),
                ('Branch_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Floor', models.CharField(blank=True, max_length=200, null=True)),
                ('Auction_No', models.IntegerField(blank=True, null=True)),
                ('MakeCode', models.CharField(blank=True, max_length=200, null=True)),
                ('Brand_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Model_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Sub_Model_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Sub_Key', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Gear', models.CharField(blank=True, max_length=200, null=True)),
                ('Engine_Size', models.FloatField(blank=True, null=True)),
                ('Chassis_No', models.CharField(blank=True, max_length=200, null=True)),
                ('Engine_No', models.CharField(blank=True, max_length=200, null=True)),
                ('Mile', models.FloatField(blank=True, null=True)),
                ('Color_in_copy', models.CharField(blank=True, max_length=200, null=True)),
                ('Year_of_Manufacture', models.IntegerField(blank=True, null=True)),
                ('Asset_Register_Year', models.FloatField(blank=True, null=True)),
                ('Asset_Type_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Type_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Group_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Group_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Grade_Assessment', models.CharField(blank=True, max_length=200, null=True)),
                ('Sales_Price', models.FloatField(blank=True, null=True)),
                ('Vat_Amount', models.FloatField(blank=True, null=True)),
                ('VAT_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Vat_Percentage', models.IntegerField(blank=True, null=True)),
                ('Price_including_VAT', models.FloatField(blank=True, null=True)),
                ('Seller_Approve_Sales_Price', models.IntegerField(blank=True, null=True)),
                ('Approve_Sales_Price', models.IntegerField(blank=True, null=True)),
                ('Sold_Amount', models.FloatField(blank=True, null=True)),
                ('Sales_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Contract_No', models.CharField(blank=True, max_length=200, null=True)),
                ('License_Plate_No', models.CharField(blank=True, max_length=200, null=True)),
                ('License_Plate_City', models.CharField(blank=True, max_length=200, null=True)),
                ('License_Plate_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Seller_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Highest_Selling_Price', models.IntegerField(blank=True, null=True)),
                ('Asset_Tax_Due_Date', models.CharField(blank=True, max_length=200, null=True)),
                ('Accessories', models.FloatField(blank=True, null=True)),
                ('Auction_Board', models.IntegerField(blank=True, null=True)),
                ('Asset_Grade', models.CharField(blank=True, max_length=200, null=True)),
                ('Asset_Grade_Check_Condition', models.CharField(blank=True, max_length=200, null=True)),
                ('Vendor_No', models.CharField(blank=True, max_length=200, null=True)),
                ('Vendor_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Vendor_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('Vehiclekey', models.CharField(blank=True, max_length=200, null=True)),
                ('BodyStyleDescription', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
