# Generated by Django 4.2 on 2026-03-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenbook', '0004_asset_sold_car_2024_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_sold_car_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.DateField(blank=True, null=True)),
                ('byquater', models.IntegerField(blank=True, null=True)),
                ('bymonth', models.IntegerField(blank=True, null=True)),
                ('month_name', models.CharField(blank=True, max_length=200, null=True)),
                ('byseasonal', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_code', models.IntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('floor', models.CharField(blank=True, max_length=200, null=True)),
                ('auction_no', models.IntegerField(blank=True, null=True)),
                ('makecode', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_model_code', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_key', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_gear', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_size', models.FloatField(blank=True, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=200, null=True)),
                ('mile', models.FloatField(blank=True, null=True)),
                ('color_in_copy', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('asset_register_year', models.FloatField(blank=True, null=True)),
                ('asset_type_code', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_group_code', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_grade_assessment', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_price', models.FloatField(blank=True, null=True)),
                ('vat_amount', models.FloatField(blank=True, null=True)),
                ('vat_code', models.CharField(blank=True, max_length=200, null=True)),
                ('vat_percentage', models.IntegerField(blank=True, null=True)),
                ('price_including_vat', models.FloatField(blank=True, null=True)),
                ('seller_approve_sales_price', models.IntegerField(blank=True, null=True)),
                ('approve_sales_price', models.IntegerField(blank=True, null=True)),
                ('sold_amount', models.FloatField(blank=True, null=True)),
                ('sales_type', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_no', models.CharField(blank=True, max_length=200, null=True)),
                ('license_plate_no', models.CharField(blank=True, max_length=200, null=True)),
                ('license_plate_city', models.CharField(blank=True, max_length=200, null=True)),
                ('license_plate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_code', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=200, null=True)),
                ('highest_selling_price', models.IntegerField(blank=True, null=True)),
                ('asset_tax_due_date', models.CharField(blank=True, max_length=200, null=True)),
                ('accessories', models.FloatField(blank=True, null=True)),
                ('auction_board', models.IntegerField(blank=True, null=True)),
                ('asset_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_grade_check_condition', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_no', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_type', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiclekey', models.CharField(blank=True, max_length=200, null=True)),
                ('bodystyledescription', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
